language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec
addons:
  code_climate:
    repo_token: a909fe634532217548c2a59fa663bb2bad564b0218993c1a6b4e2a2d97664d51